In [20]:
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

RESULTS_ROOT = "../../results"
FINAL_DIR = "../../results/final_comparison"

os.makedirs(FINAL_DIR, exist_ok=True)

In [21]:
kmeans = pd.read_csv(f"{RESULTS_ROOT}/kmeans/kmeans_results_summary.csv")
dbscan = pd.read_csv(f"{RESULTS_ROOT}/dbscan/dbscan_grid_summary.csv")
hdbscan = pd.read_csv(f"{RESULTS_ROOT}/hdbscan/hdbscan_results_summary.csv")
ahc = pd.read_csv(f"{RESULTS_ROOT}/ahc/ahc_best_results.csv")
gmm = pd.read_csv(f"{RESULTS_ROOT}/gmm/gmm_best_results.csv")

### Standardizacija KMeans rezultata

In [22]:
kmeans_final = kmeans.copy()

kmeans_final = kmeans_final.rename(columns={
    "K": "Clusters"
})

kmeans_final["Noise_ratio"] = np.nan
kmeans_final["Selection_score"] = np.nan
kmeans_final["BIC"] = np.nan
kmeans_final["AIC"] = np.nan

kmeans_final = kmeans_final[
    [
        "Dataset",
        "Algorithm",
        "Clusters",
        "Silhouette",
        "Davies_Bouldin",
        "ARI",
        "NMI",
        "Noise_ratio",
        "Selection_score",
        "BIC",
        "AIC"
    ]
]

kmeans_final

,Dataset,Algorithm,Clusters,Silhouette,Davies_Bouldin,ARI,NMI,Noise_ratio,Selection_score,BIC,AIC
0,Scaled dataset,KMeans,4,0.2807,1.5513,0.0577,0.1389,NaN,NaN,NaN,NaN
1,PCA dataset,KMeans,4,0.2987,1.4640,0.0577,0.1388,NaN,NaN,NaN,NaN

### Standardizacija DBSCAN rezultata

In [23]:
dbscan_final = dbscan.copy()

dbscan_final = dbscan_final.rename(columns={
    "Silhouette_non_noise": "Silhouette",
    "Davies_Bouldin_non_noise": "Davies_Bouldin"
})

dbscan_final["BIC"] = np.nan
dbscan_final["AIC"] = np.nan

dbscan_final = dbscan_final[
    [
        "Dataset",
        "Algorithm",
        "Clusters",
        "Silhouette",
        "Davies_Bouldin",
        "ARI",
        "NMI",
        "Noise_ratio",
        "Selection_score",
        "BIC",
        "AIC"
    ]
]

dbscan_final

,Dataset,Algorithm,Clusters,Silhouette,Davies_Bouldin,ARI,NMI,Noise_ratio,Selection_score,BIC,AIC
0,Scaled dataset,DBSCAN,11,0.2201,1.1712,0.0274,0.0958,0.4522,-0.2321,NaN,NaN
1,PCA dataset,DBSCAN,10,0.2055,0.9490,0.0267,0.0938,0.4463,-0.2408,NaN,NaN

### Standardizacija HDBSCAN rezultata

In [24]:
hdbscan_final = hdbscan.copy()

hdbscan_final = hdbscan_final.rename(columns={
    "Silhouette_non_noise": "Silhouette",
    "Davies_Bouldin_non_noise": "Davies_Bouldin"
})

hdbscan_final["BIC"] = np.nan
hdbscan_final["AIC"] = np.nan

hdbscan_final = hdbscan_final[
    [
        "Dataset",
        "Algorithm",
        "Clusters",
        "Silhouette",
        "Davies_Bouldin",
        "ARI",
        "NMI",
        "Noise_ratio",
        "Selection_score",
        "BIC",
        "AIC"
    ]
]

hdbscan_final

,Dataset,Algorithm,Clusters,Silhouette,Davies_Bouldin,ARI,NMI,Noise_ratio,Selection_score,BIC,AIC
0,Scaled dataset,HDBSCAN,5,0.2721,1.3551,0.0268,0.0673,0.3458,0.2569,NaN,NaN
1,PCA dataset,HDBSCAN,3,0.3958,0.7061,0.0221,0.0517,0.3272,0.2803,NaN,NaN

### Standardizacija AHC rezultata

In [25]:
ahc_final = ahc.copy()

ahc_final = ahc_final.rename(columns={
    "K": "Clusters"
})

ahc_final["Algorithm"] = "AHC"
ahc_final["Noise_ratio"] = np.nan
ahc_final["Selection_score"] = np.nan
ahc_final["BIC"] = np.nan
ahc_final["AIC"] = np.nan

ahc_final = ahc_final[
    [
        "Dataset",
        "Algorithm",
        "Clusters",
        "Silhouette",
        "Davies_Bouldin",
        "ARI",
        "NMI",
        "Noise_ratio",
        "Selection_score",
        "BIC",
        "AIC"
    ]
]

ahc_final

,Dataset,Algorithm,Clusters,Silhouette,Davies_Bouldin,ARI,NMI,Noise_ratio,Selection_score,BIC,AIC
0,PCA dataset,AHC,2,0.4949,0.8028,0.0028,0.0056,NaN,NaN,NaN,NaN
1,Scaled dataset,AHC,2,0.4827,0.8263,0.0047,0.0093,NaN,NaN,NaN,NaN

### Standardizacija GMM rezultata

In [26]:
gmm_final = gmm.copy()

gmm_final = gmm_final.rename(columns={
    "K": "Clusters"
})

gmm_final["Noise_ratio"] = np.nan
gmm_final["Selection_score"] = np.nan

gmm_final = gmm_final[
    [
        "Dataset",
        "Algorithm",
        "Clusters",
        "Silhouette",
        "Davies_Bouldin",
        "ARI",
        "NMI",
        "Noise_ratio",
        "Selection_score",
        "BIC",
        "AIC"
    ]
]

gmm_final

,Dataset,Algorithm,Clusters,Silhouette,Davies_Bouldin,ARI,NMI,Noise_ratio,Selection_score,BIC,AIC
0,PCA dataset,GMM,14,-0.0658,3.3168,0.0525,0.1333,NaN,NaN,189987.15,180504.82
1,Scaled dataset,GMM,14,0.1297,2.4912,0.0998,0.2195,NaN,NaN,181159.83,134039.43

# Spajanje svih rezultata

In [27]:
final_comparison = pd.concat(
    [
        kmeans_final,
        dbscan_final,
        hdbscan_final,
        ahc_final,
        gmm_final
    ],
    ignore_index=True
)

final_comparison = final_comparison.round({
    "Silhouette": 4,
    "Davies_Bouldin": 4,
    "ARI": 4,
    "NMI": 4,
    "Noise_ratio": 4,
    "Selection_score": 4,
    "BIC": 2,
    "AIC": 2
})

final_comparison.to_csv(
    f"{FINAL_DIR}/final_comparison_summary.csv",
    index=False
)

final_comparison

,Dataset,Algorithm,Clusters,Silhouette,Davies_Bouldin,ARI,NMI,Noise_ratio,Selection_score,BIC,AIC
0,Scaled dataset,KMeans,4,0.2807,1.5513,0.0577,0.1389,NaN,NaN,NaN,NaN
1,PCA dataset,KMeans,4,0.2987,1.4640,0.0577,0.1388,NaN,NaN,NaN,NaN
2,Scaled dataset,DBSCAN,11,0.2201,1.1712,0.0274,0.0958,0.4522,-0.2321,NaN,NaN
3,PCA dataset,DBSCAN,10,0.2055,0.9490,0.0267,0.0938,0.4463,-0.2408,NaN,NaN
4,Scaled dataset,HDBSCAN,5,0.2721,1.3551,0.0268,0.0673,0.3458,0.2569,NaN,NaN
5,PCA dataset,HDBSCAN,3,0.3958,0.7061,0.0221,0.0517,0.3272,0.2803,NaN,NaN
6,PCA dataset,AHC,2,0.4949,0.8028,0.0028,0.0056,NaN,NaN,NaN,NaN
7,Scaled dataset,AHC,2,0.4827,0.8263,0.0047,0.0093,NaN,NaN,NaN,NaN
8,PCA dataset,GMM,14,-0.0658,3.3168,0.0525,0.1333,NaN,NaN,189987.15,180504.82
9,Scaled dataset,GMM,14,0.1297,2.4912,0.0998,0.2195,NaN,NaN,181159.83,134039.43

### Najbolji algoritmi po metrikama

In [28]:
best_by_dataset = []

for dataset_name, group in final_comparison.groupby("Dataset"):
    row = {
        "Dataset": dataset_name
    }

    best_silhouette = group.loc[group["Silhouette"].idxmax()]
    row["Best_by_Silhouette"] = best_silhouette["Algorithm"]
    row["Best_Silhouette"] = best_silhouette["Silhouette"]

    best_davies = group.loc[group["Davies_Bouldin"].idxmin()]
    row["Best_by_Davies_Bouldin"] = best_davies["Algorithm"]
    row["Best_Davies_Bouldin"] = best_davies["Davies_Bouldin"]

    best_ari = group.loc[group["ARI"].idxmax()]
    row["Best_by_ARI"] = best_ari["Algorithm"]
    row["Best_ARI"] = best_ari["ARI"]

    best_nmi = group.loc[group["NMI"].idxmax()]
    row["Best_by_NMI"] = best_nmi["Algorithm"]
    row["Best_NMI"] = best_nmi["NMI"]

    best_by_dataset.append(row)

best_by_dataset = pd.DataFrame(best_by_dataset)

best_by_dataset.to_csv(
    f"{FINAL_DIR}/best_algorithm_by_dataset.csv",
    index=False
)

best_by_dataset

,Dataset,Best_by_Silhouette,Best_Silhouette,Best_by_Davies_Bouldin,Best_Davies_Bouldin,Best_by_ARI,Best_ARI,Best_by_NMI,Best_NMI
0,PCA dataset,AHC,0.4949,HDBSCAN,0.7061,KMeans,0.0577,KMeans,0.1388
1,Scaled dataset,AHC,0.4827,AHC,0.8263,GMM,0.0998,GMM,0.2195

### Grafici za Silhouette, ARI i NMI

In [29]:
metrics_to_plot = ["Silhouette", "ARI", "NMI"]

for metric in metrics_to_plot:
    plt.figure(figsize=(10, 5))

    sns.barplot(
        data=final_comparison,
        x="Algorithm",
        y=metric,
        hue="Dataset"
    )

    plt.title(f"Final comparison by {metric}")
    plt.xlabel("Algorithm")
    plt.ylabel(metric)
    plt.xticks(rotation=30)
    plt.tight_layout()

    filename = f"{FINAL_DIR}/final_comparison_{metric.lower()}.png"
    plt.savefig(filename, dpi=200)
    plt.close()

    print(f"Saved: {filename}")

Saved: ../../results/final_comparison/final_comparison_silhouette.png
Saved: ../../results/final_comparison/final_comparison_ari.png
Saved: ../../results/final_comparison/final_comparison_nmi.png

### Grafikon za Davies-Bouldin

In [30]:
plt.figure(figsize=(10, 5))

sns.barplot(
    data=final_comparison,
    x="Algorithm",
    y="Davies_Bouldin",
    hue="Dataset"
)

plt.title("Final comparison by Davies-Bouldin score lower is better")
plt.xlabel("Algorithm")
plt.ylabel("Davies-Bouldin")
plt.xticks(rotation=30)
plt.tight_layout()

filename = f"{FINAL_DIR}/final_comparison_davies_bouldin.png"
plt.savefig(filename, dpi=200)
plt.close()

print(f"Saved: {filename}")

Saved: ../../results/final_comparison/final_comparison_davies_bouldin.png

### Dodatni grafikon: noise ratio samo za DBSCAN/HDBSCAN

In [31]:
density_algorithms = final_comparison[
    final_comparison["Algorithm"].isin(["DBSCAN", "HDBSCAN"])
]

plt.figure(figsize=(8, 5))

sns.barplot(
    data=density_algorithms,
    x="Algorithm",
    y="Noise_ratio",
    hue="Dataset"
)

plt.title("Noise ratio for density-based clustering algorithms")
plt.xlabel("Algorithm")
plt.ylabel("Noise ratio")
plt.xticks(rotation=30)
plt.tight_layout()

filename = f"{FINAL_DIR}/final_comparison_noise_ratio.png"
plt.savefig(filename, dpi=200)
plt.close()

print(f"Saved: {filename}")

Saved: ../../results/final_comparison/final_comparison_noise_ratio.png

### Dodatni grafikon: selection score samo za DBSCAN/HDBSCAN

In [32]:
plt.figure(figsize=(8, 5))

sns.barplot(
    data=density_algorithms,
    x="Algorithm",
    y="Selection_score",
    hue="Dataset"
)

plt.title("Selection score for density-based clustering algorithms")
plt.xlabel("Algorithm")
plt.ylabel("Selection score")
plt.xticks(rotation=30)
plt.tight_layout()

filename = f"{FINAL_DIR}/final_comparison_selection_score.png"
plt.savefig(filename, dpi=200)
plt.close()

print(f"Saved: {filename}")

Saved: ../../results/final_comparison/final_comparison_selection_score.png

### GMM BIC/AIC posebna tabela

In [33]:
gmm_best_model_selection = gmm[
    [
        "Dataset",
        "Algorithm",
        "Covariance",
        "K",
        "BIC",
        "AIC"
    ]
].copy()

gmm_best_model_selection.to_csv(
    f"{FINAL_DIR}/gmm_best_model_selection_summary.csv",
    index=False
)

gmm_best_model_selection

          Dataset Algorithm Covariance   K        BIC        AIC
0     PCA dataset       GMM       diag  14  189987.15  180504.82
1  Scaled dataset       GMM       diag  14  181159.83  134039.43

### The final comparison combines the best configuration of each clustering algorithm for both datasets. Internal metrics such as Silhouette and Davies-Bouldin evaluate the geometric structure of the clusters, while ARI and NMI compare the obtained clusters with the true expression labels.

### For DBSCAN and HDBSCAN, Silhouette and Davies-Bouldin were computed only on non-noise points, because noise points are not regular clusters. Their Noise ratio and Selection score were therefore included separately.

### The results show that different algorithms optimize different aspects of the problem. Some methods produce better internal cluster separation, while others show slightly better agreement with the true expression labels. Overall, the low ARI and NMI values indicate that the expression classes are not clearly separated in the selected feature space.